# Generated by Django 5.2.5 on 2026-03-08 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('products', '0002_product_products_pr_name_9ff0a3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['product'], name='inventory_i_product_a29bca_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['created_at'], name='inventory_i_created_b93ae4_idx'),
        ),
    ]
